function [C_m, C_m_uncertainty] = fn_get_C_m(libration_amplitude, la_uncertainty)
    to_radians = 2*pi/(360*60*60);
    f_of_e_c = @(e_c) 1 - 11*e_c^2 + 959/48 * e_c^4;
    eccentricity = 0.20563;  % Baland 2017
    C_22 = .80389e-5;  % Baland 2017
    R = 2439.36e3;
    R_uncertainty = 0.02e3;
    M = 3.30111e23;
    M_uncertainty = 0.00015e23;
    C_m = M*R^2 * 6 * f_of_e_c(eccentricity) * C_22 / ...
        (libration_amplitude*to_radians);
    C_m_uncertainty_from_la = abs(M*R^2 * 6 * f_of_e_c(eccentricity) * C_22 / ...
        (libration_amplitude*to_radians)^2) * la_uncertainty*to_radians;
    C_m_uncertainty_from_M = abs(R^2 * 6 * f_of_e_c(eccentricity) * C_22 / ...
        (libration_amplitude*to_radians)) * M_uncertainty;
    C_m_uncertainty_from_R = abs(M*2*R * 6 * f_of_e_c(eccentricity) * C_22 / ...
        (libration_amplitude*to_radians)) * R_uncertainty;
    C_m_uncertainty = ...
        C_m_uncertainty_from_la + ...
        C_m_uncertainty_from_M + ...
        C_m_uncertainty_from_R;
end